### ISSUE TITLE
Alpha falis for perfect relibility

### ISSUE THREAD

**Issue by thoppe** [grrrr/krippendorff-alpha#1]
Minimal working example

    array = [[1,1,1],[1,1,1],[1,1,1]]   
    print("nominal metric: %.3f" % krippendorff_alpha(array, nominal_metric, missing_items=missing))
    print("interval metric: %.3f" % krippendorff_alpha(array, interval_metric, missing_items=missing))

Output

```
./krippendorff_alpha.py:103: RuntimeWarning: invalid value encountered in double_scalars
  return 1.-Do/De
nominal metric: nan
interval metric: nan
```

If I understand Krippendorff Alpha, the expected output should be one for all metrics. I'm not sure what should be done if there are missing values.

**Comment by grrrr** [comment]
Thank you, that is corrected.
